# Generated by Django 5.1.4 on 2026-07-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0023_alter_clothessizecolorstock_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clothessizecolorstock',
            unique_together={('product', 'size', 'color')},
        ),
    ]
